from pathlib import Path
from semver import VersionInfo
from flit.build import main as flit_build

from pyship import rmdir, mkdirs

TST_APP_NAME = "tstpyshipapp"
TST_APP_VERSION = VersionInfo(1, 2, 3)
TST_APP_PROJECT_DIR = Path("test_pyship", TST_APP_NAME)
TST_APP_DIST_DIR = Path(TST_APP_PROJECT_DIR, "dist")
TST_APP_FROZEN_PARENT = Path(TST_APP_PROJECT_DIR, "frozen")
TST_APP_FROZEN_DIR = Path(TST_APP_FROZEN_PARENT, TST_APP_NAME)
TST_APP_LAUNCHER_EXE_PATH = Path(TST_APP_FROZEN_DIR, TST_APP_NAME, f"{TST_APP_NAME}.exe")
TST_APP_CACHE = Path(TST_APP_PROJECT_DIR, "cache")


def write_test_app_version(version: VersionInfo):
    module_dir = Path(TST_APP_PROJECT_DIR, TST_APP_NAME)
    rmdir(Path(module_dir, "__pycache__"))  # to be safe ...
    with open(Path(module_dir, "__version__.py"), "w") as f:
        f.write("\n".join([f"# automatically generated by {__name__}", f'__version__ = "{str(version)}"', ""]))


def test_app_flit_build():
    mkdirs(TST_APP_DIST_DIR, remove_first=True)
    flit_build(Path(TST_APP_PROJECT_DIR, "pyproject.toml"))  # use flit to build the target app into a distributable package in the "dist" directory
